from typing import Any

from pydantic import BaseModel, Field, field_validator


class ExecutionPlanStep(BaseModel):
    """Validated unit of work produced by the agent planner."""

    id: str = Field(..., min_length=1)
    task: str = Field(..., min_length=1)
    tool: str = Field(..., min_length=1)
    depends_on: list[str] = Field(default_factory=list)
    files: list[str] = Field(default_factory=list)
    status: str = Field(default="pending")
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("status")
    @classmethod
    def validate_status(cls, value: str) -> str:
        allowed = {"pending", "running", "completed", "failed"}
        if value not in allowed:
            raise ValueError(f"Invalid step status: {value}")
        return value


class ExecutionPlan(BaseModel):
    """Validated execution plan generated by the agent planner."""

    plan_id: str = Field(..., min_length=1)
    summary: str = Field(default="")
    steps: list[ExecutionPlanStep] = Field(default_factory=list)
    affected_files: list[str] = Field(default_factory=list)
    test_plan: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("steps")
    @classmethod
    def validate_steps(cls, steps: list[ExecutionPlanStep]) -> list[ExecutionPlanStep]:
        ids = [step.id for step in steps]

        if len(ids) != len(set(ids)):
            raise ValueError("Execution plan contains duplicate step IDs")

        step_ids = set(ids)

        for step in steps:
            unknown_dependencies = set(step.depends_on) - step_ids
            if unknown_dependencies:
                raise ValueError(
                    f"Step '{step.id}' contains unknown dependencies: "
                    f"{sorted(unknown_dependencies)}"
                )

        return steps